name: trading
channels:
  - conda-forge
dependencies:
  - ipykernel==6.30.0
  - numpy==1.26.4
  - pandas==2.3.1
  - pip==25.2
  - plotly==6.3.0
  - python==3.12.11
  - python-dotenv==1.2.1
  - requests==2.32.5
  - rich==14.2.0
  - pydantic==2.12.5
  - streamlit==1.47.0
  - yaml==0.2.5
  - pip:
      - -r requirements.txt
